
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.Expander expander1;

	private global::Gtk.Expander expander2;

	private global::Gtk.Expander expander3;

	private global::Gtk.Label GtkLabel2;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.Label GtkLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table(((uint)(1)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.expander1 = new global::Gtk.Expander(null);
		this.expander1.CanFocus = true;
		this.expander1.Name = "expander1";
		this.expander1.Expanded = true;
		// Container child expander1.Gtk.Container+ContainerChild
		this.expander2 = new global::Gtk.Expander(null);
		this.expander2.CanFocus = true;
		this.expander2.Name = "expander2";
		this.expander2.Expanded = true;
		// Container child expander2.Gtk.Container+ContainerChild
		this.expander3 = new global::Gtk.Expander(null);
		this.expander3.CanFocus = true;
		this.expander3.Name = "expander3";
		this.expander3.Expanded = true;
		this.GtkLabel2 = new global::Gtk.Label();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("GtkExpander");
		this.GtkLabel2.UseUnderline = true;
		this.expander3.LabelWidget = this.GtkLabel2;
		this.expander2.Add(this.expander3);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("GtkExpander");
		this.GtkLabel1.UseUnderline = true;
		this.expander2.LabelWidget = this.GtkLabel1;
		this.expander1.Add(this.expander2);
		this.GtkLabel = new global::Gtk.Label();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("GtkExpander");
		this.GtkLabel.UseUnderline = true;
		this.expander1.LabelWidget = this.GtkLabel;
		w1.Add(this.expander1);
		this.GtkScrolledWindow.Add(w1);
		this.table2.Add(this.GtkScrolledWindow);
		this.Add(this.table2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 922;
		this.DefaultHeight = 681;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
